anchor_t: 4.0
box: 0.05
cls: 0.5
cls_pw: 1
copy_paste: 0
degrees: 0
fl_gamma: 0
fliplr: 0.5
flipud: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
iou_t: 0.2
lr0: 0.01
lrf: 0.01
mixup: 0.5
momentum: 0.937
mosaic: 0.5
obj: 1
obj_pw: 1
perspective: 0
scale: 0
shear: 0
translate: 0.1
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
